### ISSUE TITLE
Rider Support

### ISSUE THREAD

**Issue by DotNetDublin** [BlazingSolutions/TimeKeeper#43]
@jonhilt reported a problem when trying to open the application in JetBrains Rider rather than Visual Studio.

Can we document what issues occurred or put another way what within the current repository ties it specifically to Visual Studio?

**Comment by jonhilt** [comment]
This was specifically to do with the Database project.

I think there are actually ways to run the SQL files in Rider (it's just something I haven't personally tried) so I suspect we can close this issue as it hasn't stopped me working from being able to work on the project.

This also links in with a broader question around how we mutate the database (scripts vs migrations) and also how we handle this from a Docker perspective.

I think I'm inclined to close this issue in favour of those more specific conversations :-)
