### ISSUE TITLE
Validation for AddTimeEntry.razor

### ISSUE THREAD

**Issue by DotNetDublin** [BlazingSolutions/TimeKeeper#45]
Need to apply appropriate validation to AddTimeEntry.razor

As we are using MudBlazor see https://mudblazor.com/components/form

Personally I'm a fan of FluentValidation which is listed as an option however it's by no means a firm requirement.

**Comment by jonhilt** [comment]
In the refit-spike I believe we could define the fluent validation in the **Shared** project then have the dual-benefit that the rules could be applied in the browser (for convenience) but also enforced in the backend (API).

Something along these lines: https://jonhilton.net/blazor-client-server-validation-with-fluentvalidation/

**Comment by jonhilt** [comment]
I'll take this. I believe we can add a validator for `CreateTimeEntry.Command` [here](https://github.com/BlazingSolutions/TimeKeeper/blob/main/TimeKeeper.Shared/Api/Features/TimeEntry/CreateTimeEntry.cs).

I'll give it a go and see how easy it is to wire up.

**Comment by DotNetDublin** [comment]
Sounds great. Thanks @jonhilt.
